site_name: Linuxtech.io.vn
site_url: https://linuxtech.io.vn/
theme:
  name: material
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  #language: vi
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.expand
    - content.code.copy
    - search.suggest
    - search.highlight
    - search.share
  icon:
    tag:
      default: material/tag

plugins:
  - search
  - tags:
      tags_file: tags.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  &copy; 2025 <a href="https://linuxtech.io.vn"  target="_blank" rel="noopener">Linuxtech.io.vn</a>

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/thieuson1984/
    - icon: fontawesome/brands/facebook 
      link: https://www.facebook.com/ko.co.username/

nav:
  - Home: index.md
  - Linux:
    - Tổng quan: linux/index.md
    - Ubuntu: linux/ubuntu.md
    - Fedora: linux/fedora.md
  - Docker:
    - Tổng quan: docker/index.md
    - Portainer: docker/portainer.md
    - Traefik Proxy: docker/traefik.md
    - Crowdsec: docker/crowdsec.md
    - Authelia: docker/authelia.md
    - Uptime Kuma: docker/uptime-kuma.md
  - Network:
    - Tổng Quan: network/index.md
    - Adguard Home: network/adguardhome.md
  - Tags: tags.md